### ISSUE TITLE
Migrate to AWS SDK v2

### ISSUE THREAD

**Issue by cmhulbert** [saalfeldlab/n5-aws-s3#28]
Amazon announced [end-of-support fo AWS SDK for Java v1 on December 31, 2025.](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)

**Comment by bogovicj** [comment]
Today we ran into the error below.
I will temporarily set the system properties that disable this message until we address this
(which should be a high priority).

### the error
```
[WARN] The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.java.v1.disableDeprecationAnnouncement system property to 'true'.
The AWS SDK for Java 1.x is being used here:
at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
at com.amazonaws.util.VersionInfoUtils.printDeprecationAnnouncement(VersionInfoUtils.java:81)
at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:59)
at com.amazonaws.internal.EC2ResourceFetcher.<clinit>(EC2ResourceFetcher.java:44)
at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.<init>(InstanceMetadataServiceCredentialsFetcher.java:38)
at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:111)
at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:91)
at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:75)
at com.amazonaws.auth.InstanceProfileCredentialsProvider.<clinit>(InstanceProfileCredentialsProvider.java:58)
at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.initializeProvider(EC2ContainerCredentialsProviderWrapper.java:66)
at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.<init>(EC2ContainerCredentialsProviderWrapper.java:55)
at com.amazonaws.auth.DefaultAWSCredentialsProviderChain.<init>(DefaultAWSCredentialsProviderChain.java:60)
at com.amazonaws.auth.DefaultAWSCredentialsProviderChain.<clinit>(DefaultAWSCredentialsProviderChain.java:54)
at com.amazonaws.services.s3.AmazonS3ClientBuilder.standard(AmazonS3ClientBuilder.java:46)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:193)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:158)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:148)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:132)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:124)
at org.janelia.saalfeldlab.n5.s3.AmazonS3Utils.createS3(AmazonS3Utils.java:118)
```

**Comment by bogovicj** [comment]
very preliminary start here: 
https://github.com/saalfeldlab/n5-aws-s3/tree/chore/awsSdk2x

**Comment by bogovicj** [comment]
A remaining issue for custom endpoints:

in: `ExecutionInterceptorChain.modifyHttpRequestAndHttpContent` the `S3RequestSetEndpointInterceptor` appears to modify the http request, adding the bucket name (?) as a prefix to the host

e.g. if the client is built with
```java
s3 = S3Client.builder()
		.endpointOverride(N5URI.encodeAsUri("https://uk1s3.embassy.ebi.ac.uk"))
		.credentialsProvider(AnonymousCredentialsProvider.create())
		.build();
```

then the interceptor changes the host from `uk1s3.embassy.ebi.ac.uk` to `idr.uk1s3.embassy.ebi.ac.uk`

**Comment by bogovicj** [comment]
Solution to the above is to `forcePathStyle`:

```java
s3 = S3Client.builder()
		.endpointOverride(N5URI.encodeAsUri("https://uk1s3.embassy.ebi.ac.uk"))
		.forcePathStyle(true)
		.credentialsProvider(AnonymousCredentialsProvider.create())
		.build();
```

behaves as I'd expect

**Comment by bogovicj** [comment]
Tests are now passing, should still

- [ ] benchmark to ensure performance is at least as good as the current
- [ ] replace out-of-data mock test framework (likely with locally running [minio server](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html))
